import { EXP_RATE } from './consts'
import { Monster } from './graphics'
import { floor } from './utils'

type MonsterProgressionMetadata = {
  monster: Monster
  rank: number
}

// rank is actually just the total pixels, so ordered from smallest to largest
const monsterProgression: MonsterProgressionMetadata[] = [
  { monster: 'Slome', rank: 665 },
  { monster: 'See_er', rank: 729 },
  { monster: 'Haunted_Sword', rank: 920 },
  { monster: 'The_Stinger', rank: 930 },
  { monster: 'Nellyfish', rank: 961 },
  { monster: 'Slimeclops', rank: 1020 },
  { monster: 'Black_Candle_', rank: 1024 },
  { monster: 'Mad_Fish', rank: 1044 },
  { monster: 'The_Scuttler', rank: 1053 },
  { monster: 'Haniwa_Sir', rank: 1054 },
  { monster: 'Mole_Man', rank: 1116 },
  { monster: 'Centicrede', rank: 1140 },
  { monster: 'Death_Gaze', rank: 1215 },
  { monster: 'Impster', rank: 1280 },
  { monster: 'Mimicry', rank: 1360 },
  { monster: 'AstroWoman', rank: 1365 },
  { monster: 'Hypnotizer', rank: 1376 },
  { monster: 'tired_turtle', rank: 1377 },
  { monster: 'Dark_Priest', rank: 1380 },
  { monster: 'Ninji', rank: 1440 },
  { monster: 'White_Knight', rank: 1450 },
  { monster: 'Despereaux', rank: 1504 },
  { monster: 'Froad', rank: 1536 },
  { monster: 'Ghost_a_Sleep', rank: 1548 },
  { monster: 'Afterlife', rank: 1564 },
  { monster: 'Thriller', rank: 1584 },
  { monster: 'Bozo', rank: 1595 },
  { monster: 'Hob_Gobber', rank: 1596 },
  { monster: 'Dark_Nun', rank: 1617 },
  { monster: 'Glost', rank: 1620 },
  { monster: 'Mummified', rank: 1666 },
  { monster: 'NagaSan', rank: 1672 },
  { monster: 'The_Pincher', rank: 1680 },
  { monster: 'Retro_Robo', rank: 1681 },
  { monster: 'Gobber', rank: 1702 },
  { monster: 'Sporet', rank: 1716 },
  { monster: 'Bandito', rank: 1716 },
  { monster: 'Treant', rank: 1728 },
  { monster: 'Magic_Man', rank: 1748 },
  { monster: 'Clownette', rank: 1776 },
  { monster: 'Attack_Slug', rank: 1800 },
  { monster: 'El_Tigre', rank: 1804 },
  { monster: 'The_Finisher', rank: 1848 },
  { monster: 'Vampire', rank: 1872 },
  { monster: 'Cadaver', rank: 1920 },
  { monster: 'Scorbster', rank: 1935 },
  { monster: 'Crowdiction', rank: 1935 },
  { monster: 'Porcudine', rank: 1935 },
  { monster: 'Piratio', rank: 1944 },
  { monster: 'Beholden', rank: 1978 },
  { monster: 'Boldude', rank: 2000 },
  { monster: 'Madusa', rank: 2006 },
  { monster: 'Baby_Dragon', rank: 2016 },
  { monster: 'Kerpant', rank: 2024 },
  { monster: 'Sphunx', rank: 2025 },
  { monster: 'Trimoeba', rank: 2090 },
  { monster: 'Dude', rank: 2160 },
  { monster: 'Thugshroom', rank: 2162 },
  { monster: 'Mortoise', rank: 2184 },
  { monster: 'Batling', rank: 2214 },
  { monster: 'prickle_pop', rank: 2256 },
  { monster: 'Natures_Revenge', rank: 2256 },
  { monster: 'muscle_elf', rank: 2256 },
  { monster: 'z_king', rank: 2256 },
  { monster: 'wizzy_light', rank: 2256 },
  { monster: 'memory_flash', rank: 2256 },
  { monster: 'thoughtless', rank: 2256 },
  { monster: 'Cockatrix', rank: 2256 },
  { monster: 'pickle_wind', rank: 2256 },
  { monster: 'under_clam', rank: 2256 },
  { monster: 'druggy_head', rank: 2256 },
  { monster: 'wind_thief', rank: 2256 },
  { monster: 'zog', rank: 2256 },
  { monster: 'spike_o_drago', rank: 2256 },
  { monster: 'bad_battler', rank: 2256 },
  { monster: 'red_ragon', rank: 2256 },
  { monster: 'zork', rank: 2256 },
  { monster: 'zap_elf', rank: 2256 },
  { monster: 'slice_wolf', rank: 2256 },
  { monster: 'fake_mystic', rank: 2256 },
  { monster: 'bleye_dye', rank: 2256 },
  { monster: 'crush_puff', rank: 2256 },
  { monster: 'Mothaboid', rank: 2288 },
  { monster: 'kitty_demon', rank: 2304 },
  { monster: 'stone_golem', rank: 2304 },
  { monster: 'Flame_', rank: 2304 },
  { monster: 'shroom_guide', rank: 2304 },
  { monster: 'son_scream', rank: 2304 },
  { monster: 'hammer_j', rank: 2304 },
  { monster: 'portal_wolf', rank: 2304 },
  { monster: 'birdle', rank: 2304 },
  { monster: 'red_kraken', rank: 2304 },
  { monster: 'neuroto_walk', rank: 2304 },
  { monster: 'pingja', rank: 2304 },
  { monster: 'powertool_lizzy', rank: 2304 },
  { monster: 'coraler', rank: 2304 },
  { monster: 'floor_fly', rank: 2304 },
  { monster: 'cobless', rank: 2304 },
  { monster: 'polar_hand_l', rank: 2304 },
  { monster: 'archo_bat', rank: 2304 },
  { monster: 'young_monk', rank: 2304 },
  { monster: 'plower', rank: 2304 },
  { monster: 'bleel', rank: 2304 },
  { monster: 'tall_tigre', rank: 2304 },
  { monster: 'king_hoppity', rank: 2304 },
  { monster: 'lick_larry', rank: 2304 },
  { monster: 'no_box', rank: 2304 },
  { monster: 'ice_foo', rank: 2304 },
  { monster: 'mighteeta', rank: 2304 },
  { monster: 'ghost_cupid', rank: 2304 },
  { monster: 'hawaiidol', rank: 2304 },
  { monster: 'drill_doe', rank: 2304 },
  { monster: 'tri_bite', rank: 2304 },
  { monster: 'druggy_hand_r', rank: 2304 },
  { monster: 'snotogre', rank: 2304 },
  { monster: 'meal_metal', rank: 2304 },
  { monster: 'point_lobster', rank: 2304 },
  { monster: 'zentipede', rank: 2304 },
  { monster: 'wind_wizard', rank: 2304 },
  { monster: 'bad_general', rank: 2304 },
  { monster: 'roove', rank: 2304 },
  { monster: 'flare_flow', rank: 2304 },
  { monster: 'king_james_violet', rank: 2304 },
  { monster: 'sole_fuego', rank: 2304 },
  { monster: 'droolzy', rank: 2304 },
  { monster: 'water_wham', rank: 2304 },
  { monster: 'box_bird', rank: 2304 },
  { monster: 'cactle', rank: 2304 },
  { monster: 'flash_elf', rank: 2304 },
  { monster: 'mighty_mouse', rank: 2304 },
  { monster: 'studded_tri', rank: 2304 },
  { monster: 'shull_kield', rank: 2304 },
  { monster: 'maskete', rank: 2304 },
  { monster: 'mystery_moth', rank: 2304 },
  { monster: 'grump', rank: 2304 },
  { monster: 'pentaserpent', rank: 2304 },
  { monster: 'pegacorn', rank: 2304 },
  { monster: 'employee_hook', rank: 2304 },
  { monster: 'baby_poop', rank: 2304 },
  { monster: 'flake_fairy', rank: 2304 },
  { monster: 'blackmack', rank: 2304 },
  { monster: 'baffle_ice', rank: 2304 },
  { monster: 'galapuddle', rank: 2304 },
  { monster: 'war_turtle', rank: 2304 },
  { monster: 'jelly_crawl', rank: 2304 },
  { monster: 'grayngel', rank: 2304 },
  { monster: 'memoranha', rank: 2304 },
  { monster: 'pegawk', rank: 2304 },
  { monster: 'hot_cold_kid', rank: 2304 },
  { monster: 'phony_prophet', rank: 2304 },
  { monster: 'terror_tree', rank: 2304 },
  { monster: 'last_war_bird', rank: 2304 },
  { monster: 'mecha_bull', rank: 2304 },
  { monster: 'vulfur', rank: 2304 },
  { monster: 'solo_deemo', rank: 2304 },
  { monster: 'sleepy_doom', rank: 2304 },
  { monster: 'sprout_slime', rank: 2304 },
  { monster: 'tough_worm', rank: 2304 },
  { monster: 'tiny_daughter', rank: 2304 },
  { monster: 'cracked_pharaoh', rank: 2304 },
  { monster: 'shallow_hands', rank: 2304 },
  { monster: 'never_gnome', rank: 2304 },
  { monster: 'raptorrior', rank: 2304 },
  { monster: 'row__column_', rank: 2304 },
  { monster: 'sflish', rank: 2304 },
  { monster: 'jelliquid', rank: 2304 },
  { monster: 'stone_gold_augustine', rank: 2304 },
  { monster: 'crop_slop', rank: 2304 },
  { monster: 'wisp_wizard', rank: 2304 },
  { monster: 'half_zeus', rank: 2304 },
  { monster: 'scorpo', rank: 2304 },
  { monster: 'bae_hoe', rank: 2304 },
  { monster: 'valet_golem', rank: 2304 },
  { monster: 'flim_flam', rank: 2304 },
  { monster: 'toolbot', rank: 2304 },
  { monster: 'champ_son', rank: 2304 },
  { monster: 'slash_shadow', rank: 2304 },
  { monster: 'low_wolf', rank: 2304 },
  { monster: 'spiker', rank: 2304 },
  { monster: 'crab_high', rank: 2304 },
  { monster: 'bee_fall', rank: 2304 },
  { monster: 'manny_pup', rank: 2304 },
  { monster: 'skele_ruby', rank: 2304 },
  { monster: 'pincer_pinch', rank: 2304 },
  { monster: 'earth_wind_warrior', rank: 2304 },
  { monster: 'horned_hornet', rank: 2304 },
  { monster: 'orco_fro', rank: 2304 },
  { monster: 'arachnoid', rank: 2304 },
  { monster: 'double_dog', rank: 2304 },
  { monster: 'hissy_slide', rank: 2304 },
  { monster: 'sci_fi_centaur', rank: 2304 },
  { monster: 'skele_deep', rank: 2304 },
  { monster: 'slith', rank: 2304 },
  { monster: 'divinifly', rank: 2304 },
  { monster: 'salaheat', rank: 2304 },
  { monster: 'octolight', rank: 2304 },
  { monster: 'dust_golem', rank: 2304 },
  { monster: 'demon_purple', rank: 2304 },
  { monster: 'st_jason', rank: 2304 },
  { monster: 'boodalf', rank: 2304 },
  { monster: 'flowick', rank: 2304 },
  { monster: 'crazy_tim', rank: 2304 },
  { monster: 'good_chef', rank: 2304 },
  { monster: 'half_on_orc', rank: 2304 },
  { monster: 'GlutWyrm', rank: 2304 },
  { monster: 'cyclobber', rank: 2304 },
  { monster: 'ruby_dragonette', rank: 2304 },
  { monster: 'pencil_boy', rank: 2304 },
  { monster: 'unihorn', rank: 2304 },
  { monster: 'papa_poop', rank: 2304 },
  { monster: 'magnet_devil', rank: 2304 },
  { monster: 'ice_orc', rank: 2304 },
  { monster: 'grayja', rank: 2304 },
  { monster: 'party_drill', rank: 2304 },
  { monster: 'demon_dork', rank: 2304 },
  { monster: 'fight_wife', rank: 2304 },
  { monster: 'wonder_girl', rank: 2304 },
  { monster: 'womantis', rank: 2304 },
  { monster: 'awe_slug', rank: 2304 },
  { monster: 'double_roo', rank: 2304 },
  { monster: 'standoffrus', rank: 2304 },
  { monster: 'johnny_droop', rank: 2304 },
  { monster: 'sandy_max', rank: 2304 },
  { monster: 'her_spark', rank: 2304 },
  { monster: 'greatoucan', rank: 2304 },
  { monster: 'water_boo', rank: 2304 },
  { monster: 'sharp_alpha', rank: 2304 },
  { monster: 'frozenstein', rank: 2304 },
  { monster: 'one_kay_idol', rank: 2304 },
  { monster: 'cubey', rank: 2304 },
  { monster: 'apel', rank: 2304 },
  { monster: 'never_pot', rank: 2304 },
  { monster: 'dinopitch', rank: 2304 },
  { monster: 'rise_rock', rank: 2304 },
  { monster: 'schiger', rank: 2304 },
  { monster: 'polar_hand_r', rank: 2304 },
  { monster: 'fennix', rank: 2304 },
  { monster: 'chucky_drop', rank: 2304 },
  { monster: 'jump_devil', rank: 2304 },
  { monster: 'polar_head', rank: 2304 },
  { monster: 'guardian_bug', rank: 2304 },
  { monster: 'glare', rank: 2304 },
  { monster: 'shindig_robocat', rank: 2304 },
  { monster: 'flat_slither', rank: 2304 },
  { monster: 'hop_rex', rank: 2304 },
  { monster: 'susroot', rank: 2304 },
  { monster: 'shadow_clown', rank: 2304 },
  { monster: 'full_oxide', rank: 2304 },
  { monster: 'druggy_hand_l', rank: 2304 },
  { monster: 'fake_vapor', rank: 2304 },
  { monster: 'lion_rock', rank: 2304 },
  { monster: 'walkaway_swine', rank: 2304 },
  { monster: 'Wanted', rank: 2310 },
  { monster: 'The_Widower', rank: 2340 },
  { monster: 'Lizord', rank: 2340 },
  { monster: 'Boot_Lizard', rank: 2392 },
  { monster: 'Alice', rank: 2408 },
  { monster: 'Giant_Worman', rank: 2420 },
  { monster: 'Joan', rank: 2432 },
  { monster: 'Hamguard', rank: 2500 },
  { monster: 'Skrid', rank: 2538 },
  { monster: 'Dark_Knight', rank: 2597 },
  { monster: 'Sahwahgin', rank: 2655 },
  { monster: 'Man_Eater', rank: 2793 },
  { monster: 'Bad_Dog', rank: 2832 },
  { monster: 'Golem', rank: 3009 },
  { monster: 'nethette', rank: 3025 },
  { monster: 'Cultist', rank: 3249 },
  { monster: 'Yeti', rank: 3312 },
  { monster: 'False_Door', rank: 3360 },
  { monster: 'Prehistoric_Rex', rank: 3456 },
  { monster: 'Salamander', rank: 3780 },
  { monster: 'Gigantron', rank: 3782 },
  { monster: 'Tourist', rank: 4032 },
  { monster: 'Coward_', rank: 4096 },
  { monster: 'King_Grip', rank: 4248 },
  { monster: 'Executionite', rank: 4640 },
  { monster: 'Boss_Big_No', rank: 6426 },
  { monster: 'Boss_Gibbering_Atrocity', rank: 16256 },
  { monster: 'Behemoth_', rank: 16384 },
  { monster: 'Boss_Death_Majestic', rank: 18318 },
]

function getMonsterProgressionMetadata(index: number): MonsterProgressionMetadata {
  return monsterProgression[index % monsterProgression.length]!
}

function getMonsterLevel(metadata: MonsterProgressionMetadata) {
  const index = monsterProgression.findIndex(({ monster }) => monster === metadata.monster)
  const level = 1 + floor((index * 7) / 4 + 0.5)
  return level
}

function getEXPFromMonster(metadata: MonsterProgressionMetadata) {
  const level = getMonsterLevel(metadata)
  return level * EXP_RATE
}

function getMonsterHP(metadata: MonsterProgressionMetadata) {
  const level = getMonsterLevel(metadata)
  return level ** 2
}

export default getMonsterProgressionMetadata
export type { MonsterProgressionMetadata }
export { monsterProgression, getEXPFromMonster, getMonsterLevel, getMonsterHP }
